"""
Repository Interface for Doctor data access.
"""
from typing import Protocol, List, Optional, Any


class IDoctorRepository(Protocol):
    """Contract for Doctor repository operations."""

    def get_by_id(self, doctor_id: int) -> Optional[Any]: ...
    def get_by_email(self, email: str) -> Optional[Any]: ...
    def list_all(self, specialization: Optional[str] = None, search: Optional[str] = None) -> List[Any]: ...
    def create(self, name: str, specialization: str, contact_number: str, email: str, experience_years: int = 0) -> Any: ...
    def update(self, doctor_id: int, **data) -> Optional[Any]: ...
    def delete(self, doctor_id: int) -> bool: ...
