"""
Repository Interface for Patient-Doctor Mapping data access.
"""
from typing import Protocol, List, Optional, Any


class IMappingRepository(Protocol):
    """Contract for Patient-Doctor Mapping repository operations."""

    def assign(self, patient_id: int, doctor_id: int, notes: Optional[str] = None) -> Any: ...
    def get_by_id(self, mapping_id: int) -> Optional[Any]: ...
    def list_by_user(self, user_id: int) -> List[Any]: ...
    def get_by_patient(self, patient_id: int) -> List[Any]: ...
    def exists(self, patient_id: int, doctor_id: int) -> bool: ...
    def delete(self, mapping_id: int) -> bool: ...
