# Generated by Django 5.1.15 on 2026-09-04 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Assignment Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Clinical Assignment Notes')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='doctors.doctor', verbose_name='Assigned Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='patients.patient', verbose_name='Assigned Patient')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'verbose_name_plural': 'Patient-Doctor Mappings',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['patient', 'doctor'], name='idx_map_patient_doctor'), models.Index(fields=['doctor'], name='idx_map_doctor'), models.Index(fields=['-assigned_date'], name='idx_map_assigned_date')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor_mapping')],
            },
        ),
    ]
