"""
Repository Interface for Patient data access.
"""
from typing import Protocol, List, Optional, Any


class IPatientRepository(Protocol):
    """Contract for Patient repository operations with user-level scoping."""

    def get_by_id(self, patient_id: int, user_id: Optional[int] = None) -> Optional[Any]: ...
    def list_by_user(self, user_id: int, search: Optional[str] = None) -> List[Any]: ...
    def create(self, user_id: int, **data) -> Any: ...
    def update(self, patient_id: int, user_id: int, **data) -> Optional[Any]: ...
    def delete(self, patient_id: int, user_id: int) -> bool: ...
