# Generated by Django 5.1.15 on 2026-09-04 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Patient Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Patient Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Phone Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Contact Email Address')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Medical Notes & History')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Created By User')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='idx_patient_user_created'), models.Index(fields=['name'], name='idx_patient_name'), models.Index(fields=['contact_number'], name='idx_patient_contact')],
            },
        ),
    ]
