# Generated by Django 5.1.15 on 2026-09-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Doctor Full Name')),
                ('specialization', models.CharField(max_length=255, verbose_name='Medical Specialization')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Phone Number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Professional Email Address')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_doctor_email'), models.Index(fields=['specialization'], name='idx_doctor_specialization'), models.Index(fields=['name'], name='idx_doctor_name'), models.Index(fields=['-created_at'], name='idx_doctor_created_at')],
            },
        ),
    ]
